- name: Get host info
  hosts: liniiot
  gather_facts: True
  tasks:

    - name: Create user local scripts if doesn't exist
      file:
        path: /usr/local/scripts
        state: directory
        mode: '0755'
      register: cmdstd
      become: yes  
        #when: ansible_hostname == "grandmab"
    - debug:
        msg: "{{ cmdstd }}"

    - name: Copy files to local scripts
      copy:
        src: "{{ item }}" 
        dest: /usr/local/scripts/
        owner: root
        group: root
        mode: '0755'
        backup: yes
      with_items:
        - wifiiot/controller/intflapper.py
        - wifiiot/controller/mqttsub.py

      register: cmdstd
      become: yes  
        #when: ansible_hostname == "grandmab"
    - debug:
        msg: "{{ cmdstd }}"
    
    - name: copy service filesCopy script files
      copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0644'
        backup: no
      with_items:
        - wifiiot/controller/intflapper.service
        - wifiiot/controller/mqttsub.service

      register: cmdstd
      become: yes  
        #when: ansible_hostname == "grandmab"
    - debug:
        msg: "{{ cmdstd }}"
    
    - name: set int flapper service to auto-start
      register: cmdstd  
      become: yes
      systemd:
        name: intflapper.service
        daemon_reload: yes
        enabled: yes
        #when: ansible_hostname == "grandmab"
    - debug:
        msg: "{{ cmdstd }}"
    
    - name: set mqtt subscriber service to auto-start
      register: cmdstd  
      become: yes
      systemd:
        name: mqttsub.service
        daemon_reload: yes
        enabled: yes
        #when: ansible_hostname == "grandmab"
    - debug:
        msg: "{{ cmdstd }}"
    


    