---
- name: Get host info
  #hosts: 192.168.59.20
  hosts: liniiot
  gather_facts: True
  tasks:
      # Install required software packages
      - name: Upgrading 4D2 OpenPLC server to latest apt packages
        apt:
            update_cache: yes
            force_apt_get: yes
            upgrade: dist
        become: yes
        register: host_upg_stat
      - debug: var=host_upg_stat

      # Install the utilities needed
      - name: Installing base utilities
        apt: 
          update_cache: yes
          force_apt_get: yes
          name: '{{ item }}' 
          state: latest
        loop:
          - tcpdump
          - git
          - python3-rpi.gpio
          - screen
        become: yes
        register: host_pkg_add
      - debug: var=host_pkg_add

      # add git repo
      - name: Install openplc git repo
        become: yes
        git:
          repo: https://github.com/thiagoralves/OpenPLC_v3.git
          dest: /opt/openplc
      # Add break glass user

      # spin PI passwd

