---
- name: Get host info
  hosts: liniiot
  gather_facts: True
  tasks:
      # Install required software packages
      - name: Upgrading 4D2 IIOT server to latest apt packages
        apt:
            update_cache: yes
            force_apt_get: yes
            upgrade: dist
        become: yes
        register: host_upg_stat
      - debug: var=host_upg_stat

      # Install the utilities needed
      - name: Installing base utilities
        apt: 
          update_cache: yes
          force_apt_get: yes
          name: '{{ item }}' 
          state: latest
        loop:
          - tcpdump
          - git
          - motion
          - python3-rpi.gpio
          - screen
        become: yes
        register: host_pkg_add
      - debug: var=host_pkg_add
    
      - name: Configure motion application on startup
        become: yes
        lineinfile:
          path: /etc/default/motion
          regexp: '^start_motion_daemon=no'
          line: start_motion_daemon=yes
          owner: root
          group: root
          mode: '0644'
          backup: yes
         
      - name: Configure frame size & streaming
        become: yes
        lineinfile:
          path: /etc/motion/motion.conf
          regexp: '{{item.From}}'
          line: '{{item.To}}'
          owner: root
          group: root
          mode: '0644'
          state: present
          backup: yes
        with_items:
          - { From: '^framerate \d+', To: 'framerate 30'}
          - { From: '^daemon off', To: 'daemon on'}
          - { From: '^width 320', To: 'width 640' }
          - { From: '^height 240', To: 'height 480' }
          - { From: '^stream_localhost on', To: 'stream_localhost off'}
          - { From: '^stream_quality \d+', To: 'stream_quality 100'}
          - { From: '^webcontrol_localhost on', To: 'webcontrol_localhost off'}
          
      
      # Add break glass user

      # spin PI passwd

