- name: Get host info
  hosts: ssacontroller
  gather_facts: True
  tasks:
      

      # Add container user account so it can read & write stored data
      - name: "Create QTemp_Low Priv group"
        ansible.builtin.group:
          name: lpuser
          state: present
          gid: 2000
        become: yes

      - name: " create QTemp_Low Priv  user"
        ansible.builtin.user:
          name: lpuser
          shell: /usr/sbin/nologin
          comment: "Low Priv user for QTemp application"
          uid: 2000
          group: lpuser
        become: yes


      # Storage location for QTemp controller persistent storage

      - name: Create QTemp controller storage location
        ansible.builtin.file:
          path: /opt/storage/logs
          state: directory
          mode: '0755'
          owner: lpuser
          group: lpuser
        become: yes  

      - name: Create QTemp configuration storage location
        ansible.builtin.file:
          path: /opt/storage/conf
          state: directory
          mode: '0755'
          owner: lpuser
          group: lpuser
        become: yes 